export {default as Hero} from './Hero';
export {default as Login} from './Login';
export {default as Search} from './Search';
export {default as Signup} from './Signup';
export {default as Footer} from './Footer';
export {default as Navbar} from './Navbar';
export {default as Test} from './Test';
export {default as Home} from './Home';
export {default as Candidates} from './Candidates';